const { Then, setDefaultTimeout } = require('@cucumber/cucumber');

setDefaultTimeout(2 * 60000);

Then(
    'User verifies the Ranking Position page title',
    { timeout: 30000 },
    async function () {
        await this.pages.rankingPositionCreatePage.verifyRankingPositionPageTitle();
    }
);

Then(
    'User fill the Total Teams number with {int}',
    { timeout: 30000 },
    async function (totalTeams) {
        await this.pages.rankingPositionCreatePage.fillTotalTeams(totalTeams);
    }
);

Then(
    'User navigate to the Position Group Configuration and click the add button',
    { timeout: 30000 },
    async function () {
        await this.pages.rankingPositionCreatePage.navigateToPositionGroupConfigAndClickAdd();
    }
);

Then(
    'User fill the Group Name with auto-generated name on popup',
    { timeout: 30000 },
    async function () {
        await this.pages.rankingPositionCreatePage.fillGroupNameAutoGenerated();
    }
);

Then(
    'User fill the Start Position with {int} and End Position with {int}',
    { timeout: 60000 },
    async function (startPosition, endPosition) {
        await this.pages.rankingPositionCreatePage.fillStartAndEndPosition(startPosition, endPosition);
    }
);

Then(
    'User fill the Colour with {string}',
    { timeout: 30000 },
    async function (colour) {
        await this.pages.rankingPositionCreatePage.fillColour(colour);
    }
);

Then(
    'User click the Group Configuration Confirm button',
    { timeout: 30000 },
    async function () {
        await this.pages.rankingPositionCreatePage.clickGroupConfigurationConfirmButton();
    }
);
