/**
 * Class Name: CompetitionPage
 * 
 * Description: 
 * this class details about competition screen
 * 
 * @author Prem Kumar
 * @version 1.0
 * @since 12-01-2026
 */

/** @typedef {import('@playwright/test').Page} Page */
/** @typedef {import('@playwright/test').Locator} Locator */

 
const DataUtil = require("../utils/dataUtil");
const CompetitionConfigPage = require('./CompetitionConfigPage');
const { readData } = require('../utils/shareData');
let totalTeams=0;

class CompetitionPage{
    /**
  * @param {Page} page
  */

    constructor(page) {

        this.page = page;

        //Competition Page grid view
        this.createCompetition = page.locator('//span[contains(text(),"Create Competition")]');
        this.searchCompetitionCode = page.locator('(//input[@id="search_input"])[2]');
        this.selectCompetitionCode = page.locator('//span[@class="e-label"]');
        this.nextBtn = page.locator("//span[contains(text() ,'Next')]");
        this.description = page.locator('(//textarea[@placeholder="Enter Description"])[2]');
        this.totalTeamsPerCompetition = page.locator('//input[@name="name_totalTeams"]');
        this.defaultMatchDay = page.locator('//ejs-dropdownlist[@id="defaultMatchDay"]');
        this.commonCost = page.locator('//ejs-dropdownlist[@id="isCommonCost"]');
        this.allowClubCollaboration = page.locator('//ejs-dropdownlist[@id="isAllowClubCollaboration"]');
        this.fairPlay = page.locator('//ejs-dropdownlist[@id="isFairPlay"]');
        this.score = page.locator('(//ejs-dropdownlist[@id="score"]//span)[1]');
        this.useDisciplinarySanctionTable = page.locator('(//ejs-dropdownlist[@id="isUseDisciplinarySanction"]//span)[1]');
        this.autoGenerateDisciplinaryFiles = page.locator('(//ejs-dropdownlist[@id="isAutoGenerateDisciplinaryFiles"])[1]');

       //match settings
        this.minPlayersToStartGame = page.locator('//input[@name="name_minPlayers"]');
        this.maxPlayersToStartGame = page.locator('//input[@name="name_maxPlayers"]');
        this.allPlayersStarting = page.locator('//ejs-dropdownlist[@id="isAllPlayersStarting"]');
        this.presenceListRequired = page.locator('//ejs-dropdownlist[@id="isPresenceListRequired"]');
        this.hasGoalkeeper = page.locator('//ejs-dropdownlist[@id="hasGoalKeeper"]');
        this.hasSubstitution = page.locator('//ejs-dropdownlist[@id="hasSubstitution"]');
        this.minSubstitution = page.locator('//input[@id="minSubstitution"]');
        this.maxSubstitution = page.locator('//input[@id="maxSubstitution"]');
        this.hasYellowCard = page.locator('//ejs-dropdownlist[@id="hasYellowCard"]');
        this.hasRedCard = page.locator('//ejs-dropdownlist[@id="hasRedCard"]');
        this.penaltiesAllowed = page.locator('//ejs-dropdownlist[@id="isPenalitiesAllowed"]');
        this.automaticGenerationDiciplinaryFiels = page.locator('//ejs-dropdownlist[@id="isAutomaticGenerationDisciplinaryFiles"]');
        this.digitalMatchsheetRequired = page.locator('//ejs-dropdownlist[@id="isDigitalMatchsheetRequired"]');
        this.goalScrerTracking = page.locator('//ejs-dropdownlist[@id="isTrackGoalScorer"]');
        this.controlMissingIdCards = page.locator('//ejs-dropdownlist[@id="isToControlMissingIdCards"]');
        this.badWeatherCancellationDeadline = page.locator('//input[@id="badWeatherCancellationDeadline"]');

        //club changes
         this.processedAuto = page.locator('//ejs-multiselect[starts-with(@id, ej2_dropdownlist_)]');
         this.individualForfeitDeadline = page.locator('//input[@name="name_individualForfeitDeadline"]');
         this.changeDateTimeDeadline = page.locator('//input[@name="name_changeDateTimeDeadline"]');
         this.cancelGameDeadlin = page.locator('//input[@name="name_cancelGameDeadline"]');
         this.changePitchDeadline = page.locator('//input[@name="name_changePitchDeadline"]');
         this.postpondomDeadline = page.locator('//input[@name="name_postpondmentDeadline"]');

         //match function
         this.automaticDesignation = page.locator('//ejs-dropdownlist[@id="isAutomaticDesignation"]');
         this.officalCode = page.locator('//input[@name="name_officialCode"]');
         this.mettingPlace = page.locator('//ejs-dropdownlist[@id="isMeetingPlace"]');
         this.minRefereeBlock = page.locator('//input[@name="name_minRefereeBlock"]');
         this.maxrefereeBlock = page.locator('//input[@name="name_maxRefereeBlock"]');

         //pitch information
         this.squadSize = page.locator('//ejs-dropdownlist[@id="squadSize"]');
         this.pitchType = page.locator('//ejs-dropdownlist[@id="pitchType"]');
         this.averageLux = page.locator('//input[@name="name_averageLux"]');

         // next, cancel and Back button

         this.next = page.locator('//span[contains(text(),"Next")]');
         this.cancel = page.locator('//span[contains(text(),"Cancel")]');
         this.back = page.locator('//span[contains(text(),"Back")]');
         this.confirm = page.locator('//span[contains(text(),"Confirm")]');
         this.createCompetitionprogress = page.locator('//button/span[contains(text(),"Create Competition")]')

         //add competition phase oder
         this.addCompetitionPhases = page.locator('//span[contains(text(),"Add Competition Phase")]');
         this.competitionPhaseOrder = page.locator('//input[@name ="name_competitionPhaseOrder"]');
         this.competitionPhaseName = page.locator('//input[@name ="name_competitionPhaseName"]');
         this.totalTeams = page.locator('//input[@name ="name_totalTeam"]');
         this.matchGrid = page.locator('//ejs-dropdownlist[@id ="matchGrid"]');
         this.dateGrid = page.locator('//ejs-dropdownlist[@id ="dateGrid"]');
         this.generalRanking = page.locator('//ejs-dropdownlist[@id ="generalRanking"]');
         this.periodRanking = page.locator('//ejs-dropdownlist[@id ="periodRanking"]');
         this.fairplayRanking = page.locator('//ejs-dropdownlist[@id ="fairplayRanking"]');
         this.fairplayScoringWindow = page.locator('//input[@name ="name_fairplayScoringWindow"]');

         //success message
         this.bottomMessage = page.locator("//div[@class='e-toast-content' and text()='Competition created successfully!']");

         // assign teams

         this.teamsTab = page.locator("//div[@class='ng-star-inserted' and normalize-space()='Teams']")
         this.assignTeamButton = page.locator("//span[@class='whitespace-nowrap' and normalize-space()='Assign Team']");
         this.saveButton =page.locator("//button[@title='Save']");
         this.assignButton = page.locator("//span[@class='e-btn-content' and normalize-space()='Assign']");
         this.addTeamButton = page.locator("//span[@class='whitespace-nowrap' and normalize-space() ='Add Team']");
         this.searchTeam = page.locator("//input[@type='text' and @placeholder='Search Team']");
         this.teamSuccessMessage = page.locator("//div[@class='e-toast-content' and text()='Teams assigned successfully!']");
         this.firstRowCompetitionPhase = page.locator("//tbody[@role ='rowgroup']//tr[@class ='e-row' and @aria-rowindex='1']");
         this.clickFirstRecordOfCompetition = page.locator("//tr[@role='row' and @aria-rowindex='1']");
         
    }

    /**
     *  To click on create competition button
     */
    async clickOnCreateCompetitionBtn(){

         await this.createCompetition.click();
         console.log("Clicked on Create Competition button");
    }

    /**
     *  To enter competition code
     */
    async enterCompetitionCode(){

        const data = readData();
        this.competitionCode = data.competitionCode;
        await this.searchCompetitionCode.fill(this.competitionCode);
        await this.page.keyboard.type(' ');
        console.log("Entered competition code as ",this.competitionCode);

    }

    /**
     *  To click on search
     */
    async justClickOnSearch(){

        await this.searchCompetitionCode.click();
    }

    /**
     * To click on Competition config
     */
    async clickOnCompetitionConfig(){

        await this.selectCompetitionCode.click();
    }

    /**
     *  To click on next button
     */
    async clickOnNextBtn(){

        await this.nextBtn.click();
    }

    /**
     *  To enter description.
     */
    async descriptions(data){

        const value = data['Description'];

      try{

            await this.description.fill(value);
        
        } catch(error){

            console.log(`error message : ${error.message}`);
        }
    }

    /**
     *  To enter total teams per competitions
     *  It will be called in generalSettings method
     */

    async totalTeamsPerCompetitions(value){

        await this.totalTeamsPerCompetition.fill(value);
    }

    /**
     *  To enter general settings details.
     */
    async generalSettings(label, option){

        if(label ==='Total Teams per competition'){

            await this.totalTeamsPerCompetitions(option);
            console.log("Total teams per competition:",option);

        } else if(label ==='Default Match Day'){

            await this.defaultMatchDay.click();
            await this.page.getByRole('option', { name: option, exact: true }).click();
            console.log("Default Match Day :",option)

        } else if(label ==='Common Cost'){

            await this.commonCost.click();
            await this.page.getByRole('option',{name: option, exact: true}).click();
            console.log("Common Cost :",option)

        } else if(label ==='Allow Club Collaboration'){

            await this.allowClubCollaboration.click();
            await this.page.getByRole('option',{name: option, exact: true}).click();
            console.log("Allow Club Collaboration :",option)

        } else if(label ==='Fair Play'){

            await this.fairPlay.click();
            await this.page.getByRole('option',{name:option, exact:true}).click();
            console.log("Fair Play :",option)

        } else if(label ==='Score'){

            await this.score.click();
            await this.page.getByRole('option',{name: option, exact: true}).click();
            console.log("Score :",option)

        } else if( label ==='Use Disciplinary Sanction Table'){

            await this.useDisciplinarySanctionTable.click();
            await this.page.getByRole('option',{name: option, exact: true}).click();
            console.log("Use Disciplinary Sanction Table :",option)

        }else if( label ==='Auto Generate Disciplinary Files'){

            await this.autoGenerateDisciplinaryFiles.click();
            await this.page.getByRole('option',{name: option, exact: true}).click();
            console.log("Auto Generate Disciplinary Files :",option)

        }
    }

    /**
     *  To enter value in  match settings details
     */
    async matchSettings(label, option){

        if(label === 'Min Players to Start Game'){

            await this.fillMinPlayersToStartGame(option);
            console.log("Min Players to Start Game :",option);

        } else if(label === 'Max Players to Start Game'){

             await this.fillMaxPlayersToStartGame(option);
             console.log("Max Players to Start Game :",option);

        } else if(label === 'All Players Starting'){

            await this.allPlayersStarting.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("All Players Starting :",option);

        } else if (label === 'Presence List Required'){

            await this.presenceListRequired.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Presence List Required :",option);

        } else if (label === 'Has Goalkeeper'){

            await this.hasGoalkeeper.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Has Goalkeeper :",option);

        } else if(label ==='Has Substitution'){

            await this.hasSubstitution.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Has Substitution :",option);

        } else if (label ==='Min Substitution'){

            await this.fillMinSubstitution(option);
            console.log("Min Substitution :",option);

        } else if (label === 'Max Substitution'){

             await this.fillMaxSubstitution(option);
             console.log("Max Substitution :",option);

        } else if(label ==='Has Yellow Card'){
            
            await this.hasYellowCard.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Has Yellow Card :",option);

        }else if(label === 'Has Red Card'){

            await this.hasRedCard.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
             console.log("Has Red Card :",option);

        }else if(label === 'Penalties Allowed'){

            await this.penaltiesAllowed.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Penalties Allowed :",option);

        } else if (label ==='Automatic Generation Disciplinary Files'){

            await this.automaticGenerationDiciplinaryFiels.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Automatic Generation Disciplinary Files :",option);

        } else if(label ==='Digital Matchsheet Required'){

            await this.digitalMatchsheetRequired.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Digital Matchsheet Required :",option);
            

        } else if (label === 'Goal Scorer Tracking'){

            await this.goalScrerTracking.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Goal Scorer Tracking :",option);

        } else if(label ==='Control Missing ID Cards'){

            await this.controlMissingIdCards.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();
            console.log("Control Missing ID Cards :",option);

        } else if(label ==='Bad Weather Cancellation Deadlines'){

            await this.fillBadWeatherCancelDeadline(option);
            console.log("Bad Weather Cancellation Deadlines :",option);
            
        }
    }

    /**
     * To fill min players to start game
     * @param {number} value 
     * It will be called in matchSettings method
     */
    async fillMinPlayersToStartGame(value){

        await this.minPlayersToStartGame.fill(value);
    }

    /**
     * To fill max players to start game
     * @param {number} value 
     * It will be called in matchSettings method
     */
    async fillMaxPlayersToStartGame(value){

        await this.maxPlayersToStartGame.fill(value);
    }

    /**
     * To fill min substitution
     * @param {number} value 
     * It will be called in matchSettings method
     */
    async fillMinSubstitution(value){

        await this.minSubstitution.fill(value);
    }

    /**
     * To fill max subtitution
     * @param {number} value 
     * It will be called in matchSettings method
     */
     async fillMaxSubstitution(value){

        await this.maxSubstitution.fill(value);
    }

    /**
     * To fill basd weather cancel deadline
     * @param {number} value 
     * It will be called in matchSettings method
     */
    async fillBadWeatherCancelDeadline(value){

        await this.badWeatherCancellationDeadline.fill(value);
    }

    // Club changes

    async clubChanges(label, option){

        if (label === 'Processed Automatically'){

            await this.processedAuto.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

        }else if(label ==='Individual Forfeit Deadline'){

           await  this.fillIndividualForfeitDeadlines(option);

        } else if(label ==='Change Date Time Deadline'){

            await  this.fillChangeDateTimeDeadlines(option);
        } 

        else if(label ==='Cancel Game Deadline'){

            await  this.fillCancelGameDeadlines(option);
        } 
        else if(label ==='Change Pitch Deadline'){

            await  this.fillChangePitchDeadlines(option);

        } else if(label ==='Postponement Deadline'){

            await  this.fillPostpondomDeadlines(option);
        } 


    }


    async  fillIndividualForfeitDeadlines(option){

        await this.individualForfeitDeadline.fill(option);


    }

    async  fillChangeDateTimeDeadlines(option){

        await this.changeDateTimeDeadline.fill(option);


    }
    async  fillCancelGameDeadlines(option){

        await this.cancelGameDeadlin.fill(option);


    }

    async  fillChangePitchDeadlines(option){

        await this.changePitchDeadline.fill(option);


    }

     async  fillPostpondomDeadlines(option){

        await this.postpondomDeadline.fill(option);


    }

    async matchFunction(label, option){

        if (label === 'Automatic Designation'){

            await this.automaticDesignation.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

    }   else if(label === 'Official Code'){


        await this.fillOfficalCode(option);

    } else if (label ==='Meeting Place'){

       await this.mettingPlace.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

    } else if (label ==='Min Referee Block'){

         await this.minReferee(option);

    } else if(label ==='Max Referee Block'){

        await this.maxreferee(option);

    }
}

    async  fillOfficalCode(option){

        await this.officalCode.fill(option)

    }

      async  minReferee(option){

        await this.minRefereeBlock.fill(option)

    }

    async  maxreferee(option){

        await this.maxrefereeBlock.fill(option)

    }


    async pitchInformation(label, option){

        if (label ==='Squad Size'){

            await this.squadSize.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

        }else if (label === 'Pitch Type'){

             await this.pitchType.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

        }else if (label === 'Average Lux'){


            await this.fillAverageLux(option);


        }
    }


        async fillAverageLux(option){

            await this.averageLux.fill(option);

        }
    
      async nextCancelBack(label){

        switch(label){

            case "Next":
                await this.next.click();
                break;

            case "Back":
                await this.back.click();
                break;

            case "Cancel":
                await this.cancel.click();
                break;

            case "Confirm":
                await this.confirm.click();
                break;
            
            case "Create Competition":
                await this.createCompetitionprogress.click();
                break;

            default:
            
            console.log("Given label not belong to next, cancel and back");

        }
      }


      async clickOnAddCompetitionPhase(){

        await this.addCompetitionPhases.click();
      }

      async addCompetitionPhase(label, option){



        if(label ==='Competition Phase Order'){

            let competitionPhaseOder;
            competitionPhaseOder= DataUtil.getRandomNumber(1,100);
            await this.competitionPhaseOrder.fill(competitionPhaseOder);

        }else if(label === 'Competition Phase Name'){

             let competitionPhaseNames;
            competitionPhaseNames = "CompPhase"+ DataUtil.getRandomLowerAlphaNumeric();
            await this.competitionPhaseName.fill(competitionPhaseNames);
   

        }else if (label === 'Total Teams'){

            let totalTeam;
            totalTeam =DataUtil.getEvenNumber();
            await this.totalTeams.fill(totalTeam);

        }else if(label ==='Match Grid'){

            await this.matchGrid.click();
            await this.page.keyboard.press('Enter');

            

        }else if(label === 'Date Grid'){


             await this.dateGrid.click();
            await this.page.keyboard.press('Enter');

        }

         else if (label === 'General Ranking'){

            await this.generalRanking.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

        }else if (label ==='Period Ranking'){

            await this.periodRanking.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

        }else if (label ==='Fairplay Ranking'){

            await this.fairplayRanking.click();
            await this.page.getByRole('option',{name:option, exact: true}).click();

        }else if (label == 'Fairplay scorning window'){

          await this.fairplayScoringWindow.fill(option);
    
        }
        
    }

    async captureCompetitionCode(){

        this.competitionConfigPage = new CompetitionConfigPage(this.page);
        return await this.competitionConfigPage.passCompetitionCode();

    }


     async verifyMessage(){

     //await this.message.waitFor({state:'visible', timeout:2000});
      return await this.bottomMessage.innerText();   

   }

     async clickOnTab(label){

        switch (label) {
            case "Teams":
                await this.teamsTab.click(); 
                break;
        
            default:
                console.log("Tab not found");
                break;
        }


     }

     async clickOnButton(label){

        switch (label) {
            case "Assign Team":

                await this.assignTeamButton.click();
                break;
        
            case "save":
                
                await this.saveButton.click();

                break;

            case "assign ":
                await this.assignButton.click();
                break;

            case "Add Team":

                await this.addTeamButton.click();
                break;

            case"Create Data Sets":
                await this.createDataSets.click();
                break;

            default:
                break;
        }
     }

     async clickOnSearchTeam(teamName){

        await this.searchTeam.fill(teamName)
        await this.page.keyboard.press('ArrowDown');
        await this.page.keyboard.press('Enter');


     }

     async getMessageForAssignTeam(){


        return await this.teamSuccessMessage.innerText();
     }

     async clickOnFirstCompetitionPhaseFromTheGrid(){

        await this.firstRowCompetitionPhase.click();


     }

     async clickOnFirstRecordOfCompetitionScreen(){


        await this.clickFirstRecordOfCompetition.click();
     }

    }
module.exports = CompetitionPage;