/** @typedef {import('@playwright/test').Page} Page */

class RankingPositionCreatePage {
    /**
     * @param {Page} page
     */
    constructor(page) {
        this.page = page;

        // Total Teams input
        this.totalTeamsInput = page.locator(
            'input#totalTeams, input[name="name_totalTeams"], input[placeholder="Enter Total Teams"]'
        ).first();

        // Add button in Position Group Configuration grid toolbar
        this.addGroupBtn = page.locator(
            'button:has(span.e-add.e-icons):has(span.e-tbar-btn-text), ' +
            'button[aria-label="Add"]:has(span.e-add)'
        ).first();

        // Group Name input (popup)
        this.groupNameInput = page.locator(
            'input#groupName, input[name="name_groupName"], input[placeholder="Enter Group Name"]'
        ).first();

        // Start / End Position numeric inputs
        this.startPositionInput = page.locator('input[placeholder="Enter Start Position"]').first();
        this.endPositionInput = page.locator('input[placeholder="Enter End Position"]').first();

        // Confirm button (group configuration dialog)
        this.confirmBtn = page.locator('[aria-label="Confirm progress"]').first();
    }

    async verifyRankingPositionPageTitle() {
        await this.page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
        const title = this.page.locator(
            "//div[contains(@class,'e-tab-text') and contains(normalize-space(),'Ranking Position')] | " +
            "//h1[contains(normalize-space(),'Ranking Position')] | " +
            "//h2[contains(normalize-space(),'Ranking Position')] | " +
            "//span[normalize-space()='Ranking Position']"
        );
        await title.first().waitFor({ state: 'visible', timeout: 20000 });
        console.log('✓ Ranking Position page title verified');
    }

    async fillTotalTeams(totalTeams) {
        const input = await this._findInputByLabel('Total Teams', this.totalTeamsInput);
        await input.waitFor({ state: 'visible', timeout: 10000 });
        await input.scrollIntoViewIfNeeded();
        await input.click({ clickCount: 3 });
        await input.fill(String(totalTeams));
        console.log(`✓ Filled Total Teams: ${totalTeams}`);
    }

    async navigateToPositionGroupConfigAndClickAdd() {
        await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});

        const section = this.page.locator(
            '//*[contains(normalize-space(),"Position Group Configuration")]'
        ).first();
        if (await section.count() > 0) {
            await section.scrollIntoViewIfNeeded();
        }

        await this.addGroupBtn.waitFor({ state: 'visible', timeout: 15000 });
        await this.addGroupBtn.scrollIntoViewIfNeeded();
        await this.addGroupBtn.click();
        await this.page.waitForTimeout(1000);
        console.log('✓ Navigated to Position Group Configuration and clicked Add');
    }

    async fillGroupNameAutoGenerated() {
        const groupName = `Group_${Math.floor(Math.random() * 900) + 100}`;
        await this.groupNameInput.waitFor({ state: 'visible', timeout: 10000 });
        await this.groupNameInput.scrollIntoViewIfNeeded();
        await this.groupNameInput.click({ clickCount: 3 });
        await this.groupNameInput.fill(groupName);
        console.log(`✓ Filled Group Name: ${groupName}`);
    }

    async fillStartAndEndPosition(startPosition, endPosition) {
        await this.startPositionInput.waitFor({ state: 'visible', timeout: 10000 });
        await this.startPositionInput.scrollIntoViewIfNeeded();
        await this.startPositionInput.click({ clickCount: 3 });
        await this.startPositionInput.fill(String(startPosition));
        console.log(`✓ Filled Start Position: ${startPosition}`);

        await this.endPositionInput.waitFor({ state: 'visible', timeout: 10000 });
        await this.endPositionInput.scrollIntoViewIfNeeded();
        await this.endPositionInput.click({ clickCount: 3 });
        await this.endPositionInput.fill(String(endPosition));
        console.log(`✓ Filled End Position: ${endPosition}`);

        await this.page.waitForTimeout(300);
    }

    async fillColour(colour) {
        const colourInput = this.page.locator('input[placeholder="Select Colour"]').first();
        await colourInput.waitFor({ state: 'visible', timeout: 10000 });
        await colourInput.scrollIntoViewIfNeeded();
        await colourInput.click({ clickCount: 3 });
        await colourInput.fill(colour);
        await colourInput.press('Tab');
        console.log(`✓ Filled Colour: ${colour}`);
        await this.page.waitForTimeout(300);
    }

    async clickGroupConfigurationConfirmButton() {
        await this.confirmBtn.waitFor({ state: 'visible', timeout: 10000 });
        await this.confirmBtn.scrollIntoViewIfNeeded();
        await this.confirmBtn.click();
        await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
        await this.page.waitForTimeout(500);
        console.log('✓ Clicked Group Configuration Confirm button');
    }

    async _findInputByLabel(labelText, fallback) {
        const xpathBased = this.page.locator(
            `//*[contains(normalize-space(),'${labelText}')]/following::input[not(@type='hidden')][1]`
        ).first();
        if (await xpathBased.count() > 0 && await xpathBased.isVisible().catch(() => false)) {
            return xpathBased;
        }
        return fallback;
    }
}

module.exports = RankingPositionCreatePage;
